#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"$TheSkyX_Install")
echo "Installing to $TheSkyX_Path"

if [ ! -d "$TheSkyX_Path" ]; then
    echo "Coudln't find TheSkyX application location"
    exit 1
fi

if [ -d "$TheSkyX_Path/PlugIns" ]; then
	PLUGINS_DIR="$TheSkyX_Path/PlugIns"
elif [ -d "$TheSkyX_Path/Resources/Common/PlugIns64" ]; then
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns64"
else
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns"
fi

echo "Installing in $PLUGINS_DIR/PowerControlPlugIns/"

if [ ! -d "$PLUGINS_DIR/PowerControlPlugIns/" ]; then
    mkdir -p "$PLUGINS_DIR/PowerControlPlugIns/"
fi

cp -f "/tmp/PegasusPPBA_X2/powercontrollist PegasusPPBA.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/PowerControlPlugIns/PegasusPPBA.ui"
cp -f "/tmp/PegasusPPBA_X2/PegasusPPBA.ui" "$PLUGINS_DIR/PowerControlPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/PowerControlPlugIns/PegasusAstro.png"
cp -f "/tmp/PegasusPPBA_X2/PegasusAstro.png" "$PLUGINS_DIR/PowerControlPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/PowerControlPlugIns/libPegasusPPBAPower.dylib"
cp -f "/tmp/PegasusPPBA_X2/libPegasusPPBAPower.dylib" "$PLUGINS_DIR/PowerControlPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

echo "Installing in $PLUGINS_DIR/FocuserPlugIns/"

cp -f "/tmp/PegasusPPBA_X2/focuserlist PegasusPPBAExtFocuser.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/FocuserPlugIns/PegasusPPBAExtFocuser.ui"
cp -f "/tmp/PegasusPPBA_X2/PegasusPPBAExtFocuser.ui" "$PLUGINS_DIR/FocuserPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/FocuserPlugIns/PegasusAstro.png"
cp -f "/tmp/PegasusPPBA_X2/PegasusAstro.png" "$PLUGINS_DIR/FocuserPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/FocuserPlugIns/libPegasusPPBAExtFocuser.dylib"
cp -f "/tmp/PegasusPPBA_X2/libPegasusPPBAExtFocuser.dylib" "$PLUGINS_DIR/FocuserPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi


app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/powercontrollist PegasusPPBA.txt"
	chown $app_owner "$PLUGINS_DIR/PowerControlPlugIns/PegasusPPBA.ui"
	chown $app_owner "$PLUGINS_DIR/PowerControlPlugIns/PegasusAstro.png"
	chown $app_owner "$PLUGINS_DIR/PowerControlPlugIns/libPegasusPPBAPower.dylib"

	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/focuserlist PegasusPPBAExtFocuser.txt"
	chown $app_owner "$PLUGINS_DIR/FocuserPlugIns/PegasusPPBAExtFocuser.ui"
	chown $app_owner "$PLUGINS_DIR/FocuserPlugIns/PegasusAstro.png"
	chown $app_owner "$PLUGINS_DIR/FocuserPlugIns/libPegasusPPBAExtFocuser.dylib"

fi

rm -rf /tmp/PegasusPPBA_X2

